### ISSUE TITLE
Sample custom token "Not a good practice"

### ISSUE THREAD

**Issue by tab00** [axelarnetwork/interchain-token-service#91]
In your [sample custom token code](https://remix.ethereum.org/axelarnetwork/axelar-docs/blob/main/public/samples/interchain-token-iinterchaintoken.sol) it says:
```
        // Register this token (could also be done 1-time smart contract invocation)
        // Not a good practice beacuse it can't go to non-EVM chains
        deployTokenManager("");
```
What does this mean and what is good practice that we should do instead?

**Comment by re1ro** [comment]
Hey @tab00 ! Sorry for a delayed response but we are still polishing ITS and changing things here and there before the release. We will work on better examples for custom tokens.

In this case better practice would be calling `deployCustomTokenManager` [methods directly on the ITS](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interchain-token-service/InterchainTokenService.sol#L330-L369) from your deployment account rather than having the token implementation to do so.

And you can use the [StandardizedToken](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/token-implementations/StandardizedToken.sol) as a starting point rather than Sample Token example.

If you actually don't need need any additional admin or custom functionality and `StandardizedToken` completely satisfies your needs, you could just deploy it directly by calling [these ITS methods](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interchain-token-service/InterchainTokenService.sol#L371-L436). Passing distributer as address(0x0) would make it not mintable/burnable by admin/distributer. Having `StandardizedToken` with no distributor will make the token trustless as supply becomes fixed.
